# Generated by Django 5.2 on 2025-07-09 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('matches_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('form', models.CharField(max_length=5)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.manager')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('avr_rating', models.FloatField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
    ]
