# Generated by Django 5.2 on 2025-05-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=50)),
                ('matches_played', models.IntegerField()),
                ('form', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('form', models.CharField(max_length=5)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.manager')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('avr_rating', models.FloatField()),
                ('form', models.CharField(max_length=5)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
    ]
