# Generated by Django 5.2 on 2025-07-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
