# Generated by Django 5.2 on 2025-07-09 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='clubs.owner'),
        ),
    ]
