# Generated by Django 5.2 on 2025-07-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_club_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criticism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField()),
                ('time', models.DateTimeField()),
                ('likes', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.manager')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.owner')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.player')),
            ],
        ),
    ]
